osscameroon/onacut

scripts/alerts.json, scripts/fetch_eneo_alert.sh, scripts/region_ids.txt
This pull request adds a script that can be used to fetch eneo alerts and store them in an `alerts.json` file.
The `alerts.json` file can then be used (embedded)  in a vuejs frontend directly
=> feat: add script to fetch eneo alert

.github/workflows/linter.yaml, frontend/.env, frontend/.eslintignore, frontend/.eslintrc, frontend/craco.config.js, frontend/package.json, frontend/src/assets/data/Items.data.ts, frontend/src/assets/data/Links.data.ts, frontend/src/assets/themes/globals.themes.ts, frontend/src/atoms/accept.ts, frontend/src/atoms/data.ts, frontend/src/atoms/regions.ts, frontend/src/atoms/zom_leve.ts, frontend/src/modals/Modals.tsx, frontend/src/pages/streetMap/StreetMap.page.tsx, frontend/src/pages/streetMap/popupStyles.ts, frontend/src/scripts/all_list.ts, frontend/src/scripts/list_quartier.ts, frontend/src/scripts/list_ville.ts, frontend/yarn.lock
=> SetupLinter: Mise en place de la config

frontend/src/atoms/panne_btn.ts, frontend/src/modals/Modals.tsx, frontend/src/pages/home/Home.pages.tsx, frontend/src/pages/streetMap/StreetMap.page.tsx
=> HidingAlertBtn: Cacher le button lorsqu'on clique sur une alerte

frontend/src/components/city/City.component.tsx, frontend/src/components/cityDetail/CityDetail.component.tsx, frontend/src/pages/detail/Detail.page.tsx
https://user-images.githubusercontent.com/34966088/158046833-db1cb923-9eee-47d3-aa81-7b5ea8dcfa3c.mp4
=> ChangeTextStyle: set uppercase style of text

backend/onacut/api/__init__.py, backend/onacut/api/district/controllers.py, backend/onacut/api/district/fields.py, backend/onacut/api/district/parsers.py
=> implement /districts endpoint with its doc 

backend/onacut/api/__init__.py, backend/onacut/api/regions/controllers.py, backend/onacut/api/regions/fields.py, backend/onacut/api/regions/parsers.py
=> Add /regions endoints to get the list of regions(with its doc)

backend/onacut/api/alerts/controllers.py, backend/onacut/api/alerts/parsers.py
=> Implement filters on /alerts

frontend/src/atoms/details.ts, frontend/src/constants/language.ts, frontend/src/pages/detail/Detail.page.tsx
https://user-images.githubusercontent.com/34966088/158112097-9cfdcba7-dc9d-44f3-a96f-7ed7a5706b02.mp4
=> FixBugTitleOfAlertAndRefactor: I fixed the title display bug and I put the http client on the atom side

frontend/src/atoms/cities.ts, frontend/src/modals/ModalItems.tsx, frontend/src/pages/streetMap/StreetMap.page.tsx
=> StreetMap: integration endpoint of cities streetmap

frontend/Dockerfile
To launch the front-end, you must first:
- Launch the backend (Which is located in the "backend" folder, by typing this: `python3 server.py`)
- Go to the front-end folder and type this:
1. `docker build -t onacut-web .`
2. `docker run -p 3000:3000 onacut-web`
```Demo```
https://user-images.githubusercontent.com/34966088/169824093-86506fa0-0c71-4431-bac1-eb773cf9f1bd.mp4
=> DockeriseFrontEnd: Dockerization of the front-end ReactJS

backend/onacut/api/__init__.py, backend/onacut/api/cities/controllers.py, backend/requirements.txt
In case of a bad request, we were not returning cities but an empty array, this PR fix that !
=> fix: get all cities if there is a badRequest raised

backend/onacut/api/alerts/controllers.py, backend/onacut/api/cities/controllers.py, backend/onacut/api/district/controllers.py, backend/onacut/api/regions/controllers.py
- fix the BadRequest from json parser error !
=> fix: bad request error on json parser

frontend/src/components/notFound/NotFound.component.tsx, frontend/src/constants/language.ts, frontend/src/modals/ModalItems.tsx, frontend/src/pages/homeModal/HomeModal.pages.tsx
-Remove Hard coded text from files to constant file in assets
=> Feat constant

backend/onacut/api/alerts/fields.py, backend/onacut/api/cities/fields.py, backend/onacut/api/district/fields.py, backend/onacut/api/regions/fields.py
WHAT
Update the return fields of the api's endpoints so that it will be easy for the fronted dev to map the relationship between the data.
=> Format return Values of the api

frontend/src/atoms/alerts.ts, frontend/src/components/city/City.component.tsx, frontend/src/pages/list/List.pages.tsx
This PR is linked to the issue #96 
The previous display of the regions list was not caring the correct map of the total alerts display. As for now the current display is as shown below:
=> fix: total alerts displayed per region

frontend/src/constants/navigations/App.navigation.tsx
Added route for 404 page for the website.
Related issue #129 
Ilustration:
Signed-off-by: Steve Yonkeu <yokwejuste@yahoo.com>
=> feat: add route a 404 page

README.md
- Updateed root project README.md accordingly to ./backend/README.md and ./frontend/README.md
Fixes #104
=> Updated project root README.md

fastapi/onacut/main.py
- fix(fastapi): allow all host for CORS calls
=> fix(fastapi): fix the cors issue on the backend when calling from another host (wildcard(*))

frontend/package.json, frontend/src/config.ts, frontend/src/pages/detail/Detail.page.tsx, frontend/src/pages/list/List.page.tsx, frontend/src/pages/streetMap/StreetMap.page.tsx, frontend/src/routes/index.tsx, frontend/src/services/api/AlertService.ts
https://user-images.githubusercontent.com/34966088/203480716-d8771690-420b-4205-91bb-c3afff6f707a.mp4
=> Connect to the new backend

docker-compose.yml, fastapi/Dockerfile, fastapi/Makefile, frontend/.env.example, frontend/src/config.ts
- feat: updated the docker-compose
- fix: docker + makefile (database connexion)
- feat: updated the config for the backend port
- feat: we should have a skeletton of the config ./.env
=> fix: dockerfile
